WAD.APP.8302/WAD.APP.8302/Models/ErrorViewModel.cs
using System;

namespace WAD.APP._8302.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WAD.APP.8302/WAD.APP.8302/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.DBContext;
using DAL.Models;
using DAL.Repositories;

namespace WAD.APP._8302.Controllers
{
    public class CitiesController : Controller
    {
        private readonly IRepository<City> _cityRepository;
        private readonly Context _context;


        public CitiesController(IRepository<City> cityRepository, Context context)
        {
            _cityRepository = cityRepository;
            _context = context;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            return View(await _cityRepository.GetAllAsync());
        }

        // GET: Cities/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var city = await _cityRepository.GetByIdAsync(id);


            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            ViewData["CountryId"] = new SelectList(_context.Country, "Id", "Name");
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Population,Mayor,IsCapital,CountryId")] City city)
        {
            if (ModelState.IsValid)
            {
                await _cityRepository.CreateAsync(city);
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.City.FindAsync(id);
            if (city == null)
            {
                return NotFound();
            }
            ViewData["CountryId"] = new SelectList(_context.Country, "Id", "Name", city.CountryId);
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Population,Mayor,IsCapital,CountryId")] City city)
        {
            if (id != city.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(city);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryId"] = new SelectList(_context.Country, "Id", "Name", city.CountryId);
            return View(city);
        }
        // GET: Cities/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var city = await _cityRepository.GetByIdAsync(id);

            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _cityRepository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

WAD.APP.8302/WAD.APP.8302/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.DBContext;
using DAL.Models;
using DAL.Repositories;

namespace WAD.APP._8302.Controllers
{
    public class CountriesController : Controller
    {
        private readonly IRepository<Country> _countryRepository;
        public CountriesController(IRepository<Country> countryRepository)
        {
            _countryRepository = countryRepository;
        }

        // GET: Countries
        public async Task<IActionResult> Index()
        {
            return View(await _countryRepository.GetAllAsync());
        }

        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int id)
        {

            var country = await _countryRepository.GetByIdAsync(id);

            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // GET: Countries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,President,Capital,Founded,Currency")] Country country)
        {
            if (ModelState.IsValid)
            {
                await _countryRepository.CreateAsync(country);
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var country = await _countryRepository.GetByIdAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,President,Capital,Founded,Currency")] Country country)
        {
            if (id != country.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _countryRepository.UpdateAsync(country);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var country = await _countryRepository.GetByIdAsync(id);

            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _countryRepository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

WAD.APP.8302/WAD.APP.8302/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WAD.APP._8302.Models;

namespace WAD.APP._8302.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WAD.APP.8302/WAD.APP.8302/Views/Cities/Create.cshtml
@model DAL.Models.City

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>City</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mayor" class="control-label"></label>
                <input asp-for="Mayor" class="form-control" />
                <span asp-validation-for="Mayor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCapital" /> @Html.DisplayNameFor(model => model.IsCapital)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                <select asp-for="CountryId" class ="form-control" asp-items="ViewBag.CountryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WAD.APP.8302/WAD.APP.8302/Views/Cities/Delete.cshtml
@model DAL.Models.City

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Population)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Population)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mayor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mayor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCapital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCapital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WAD.APP.8302/WAD.APP.8302/Views/Cities/Details.cshtml
@model DAL.Models.City

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>City</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Population)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Population)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mayor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mayor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCapital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCapital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WAD.APP.8302/WAD.APP.8302/Views/Cities/Edit.cshtml
@model DAL.Models.City

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>City</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mayor" class="control-label"></label>
                <input asp-for="Mayor" class="form-control" />
                <span asp-validation-for="Mayor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCapital" /> @Html.DisplayNameFor(model => model.IsCapital)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WAD.APP.8302/WAD.APP.8302/Views/Cities/Index.cshtml
@model IEnumerable<DAL.Models.City>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Population)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mayor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsCapital)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Population)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mayor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCapital)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WAD.APP.8302/WAD.APP.8302/Views/Countries/Create.cshtml
@model DAL.Models.Country

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="President" class="control-label"></label>
                <input asp-for="President" class="form-control" />
                <span asp-validation-for="President" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capital" class="control-label"></label>
                <input asp-for="Capital" class="form-control" />
                <span asp-validation-for="Capital" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Founded" class="control-label"></label>
                <input asp-for="Founded" class="form-control" />
                <span asp-validation-for="Founded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label"></label>
                <input asp-for="Currency" class="form-control" />
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WAD.APP.8302/WAD.APP.8302/Views/Countries/Delete.cshtml
@model DAL.Models.Country

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.President)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.President)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Founded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Founded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WAD.APP.8302/WAD.APP.8302/Views/Countries/Details.cshtml
@model DAL.Models.Country

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.President)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.President)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Founded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Founded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WAD.APP.8302/WAD.APP.8302/Views/Countries/Edit.cshtml
@model DAL.Models.Country

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="President" class="control-label"></label>
                <input asp-for="President" class="form-control" />
                <span asp-validation-for="President" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capital" class="control-label"></label>
                <input asp-for="Capital" class="form-control" />
                <span asp-validation-for="Capital" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Founded" class="control-label"></label>
                <input asp-for="Founded" class="form-control" />
                <span asp-validation-for="Founded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label"></label>
                <input asp-for="Currency" class="form-control" />
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WAD.APP.8302/WAD.APP.8302/Views/Countries/Index.cshtml
@model IEnumerable<DAL.Models.Country>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.President)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Founded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Currency)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.President)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Founded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Currency)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WAD.APP.8302/WAD.APP.8302/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is a Portfolio task from Web Applications Development!</p>
</div>

WAD.APP.8302/WAD.APP.8302/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WAD.APP._8302</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WAD.APP._8302</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WAD.APP._8302 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>